headersOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "."
publishOrigin = "config"
commandOrigin = "config"
command = "python3 build/generate.py"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "geolocation=(), microphone=(), camera=(), interest-cohort=()"
Content-Security-Policy = "default-src 'self'; img-src 'self' data:; font-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-src 'none'; form-action 'self' mailto:"

[[headers]]
for = "/admin/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' https://api.netlify.com; object-src 'none'; base-uri 'self'; frame-src 'self'; form-action 'self'"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.html"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/content/site.json"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
from = "/readme.md"
to = "/404-not-found"
status = 404.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/README.md"
to = "/404-not-found"
status = 404.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/build/*"
to = "/404-not-found"
status = 404.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/.git/*"
to = "/404-not-found"
status = 404.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/.gitattributes"
to = "/404-not-found"
status = 404.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/.gitignore"
to = "/404-not-found"
status = 404.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/content/policies.json"
to = "/404-not-found"
status = 404.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]